apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kong/configmap.yaml
  - kong/secret.yaml
  - kong/deployment.yaml
  - kong/service.yaml
  - auth-service/pvc.yaml
  - auth-service/deployment.yaml
  - auth-service/service.yaml
  - ddos/nginx-ddos.yaml
